version: '2'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    extends:
      file: ./env.yaml
      service: env
    command: python /i3r/index.wsgi 8080 config_shell.ini
